input ProjectFilter {
    id: String
    name: String
}

# The properties that can be submitted while creating/updating a project
input ProjectInput {
    id: String
    name: String
    description: String
    technologies: [TechnologyInput],
    images: [String]
}

# The properties that can be submitted while creating/updating a technology
input TechnologyInput {
    id: String
    name: String
}

type Query {
    projects(filter: ProjectFilter): [Project]!
    project(id: ID!): Project
    technologies: [Technology]!
    technology(id: ID!): Technology
}

type Mutation {
    saveProject(project: ProjectInput): Project
}

type Project {
    id: String!
    name: String
    description: String
    technologies: [Technology]
}

type Technology {
    id: String!
    name: String
    icon: String
}

schema {
    query: Query,
    mutation: Mutation
}